[data]
data = ../data/processed/METRLA
sensors_distance = ../data/METRLA/METRLA_fixed.csv
dtw_distance = none
learn_graph = ../data/METRLA/learn_mx.pkl
column_wise = False
normalizer = std
batch_size = 64

[model]
num_of_vertices = 207
construct_type = connectivity
in_dim = 1
hidden_dims = [[64,64,64],[64,64,64],[64,64,64]]
first_layer_embedding_size = 64
out_layer_dim = 128
history = 12
horizon = 12
strides = 4
temporal_emb = True
spatial_emb = True
use_mask = True
activation = relu

[train]
seed = 1
learning_rate = 0.001
lr_decay = True
lr_decay_step = 10,20,30
lr_decay_rate = 0.1
epochs = 50
print_every = 50
save = ./garage/METRLA/
expid = 1
max_grad_norm = 5
patience = 10
log_file = ./logs/METRLA.log